export { default } from "next-auth/middleware";

export const config = {
  matcher: [
    "/dashboard/:path*",
    "/codeaudit/:path*",
    "/pixelcraft/:path*",
    "/docuwise/:path*",
    "/chatgenius/:path*",
    "/voicebox/:path*",
    "/brandspark/:path*",
    "/dataweave/:path*",
    "/mailpilot/:path*",
    "/fitforge/:path*",
    "/lexilearn/:path*",
    "/adcopy/:path*",
    "/bugbuster/:path*",
    "/pitchdeck/:path*",
    "/reciperx/:path*",
    "/stocksense/:path*",
    "/sketchai/:path*",
    "/contractiq/:path*",
    "/studyblitz/:path*",
    "/socialize/:path*",
    "/seomaster/:path*",
    "/writeflow/:path*",
    "/videosync/:path*",
    "/taskflow/:path*",
    "/securenet/:path*",
    "/apigen/:path*",
    "/travelmate/:path*",
    "/invoicepro/:path*",
    "/mindmap/:path*",
    "/realtoriq/:path*",
    "/healthpulse/:path*",
    "/profile/:path*"
  ],
};
