// Enhancement #18: Terms of Service Page
import Link from 'next/link';

export const metadata = { title: 'Terms of Service' };

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: 'var(--bg-primary)' }}>
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link href="/" className="text-sm mb-8 inline-block hover:underline" style={{ color: 'var(--accent)' }}>← Back to Home</Link>
        <h1 className="text-3xl font-bold text-gradient mb-2">Terms of Service</h1>
        <p className="text-sm mb-8" style={{ color: 'var(--text-secondary)' }}>Last updated: March 18, 2026</p>

        <div className="space-y-8" style={{ color: 'var(--text-secondary)' }}>
          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>1. Acceptance of Terms</h2>
            <p>By accessing or using AI Empire (&quot;the Platform&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>2. Description of Service</h2>
            <p>AI Empire provides AI-powered tools and services including but not limited to code auditing, image generation, document analysis, chatbot building, and 40+ additional tools. Services are provided on a subscription and token-based model.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>3. User Accounts</h2>
            <p>You must create an account to use our services. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. You must provide accurate information during registration.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>4. Payment & Subscriptions</h2>
            <p>Certain features require paid subscriptions or token purchases. All payments are processed through Stripe or Coinbase Commerce. Subscriptions auto-renew unless cancelled. Refunds are handled on a case-by-case basis.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>5. Token System</h2>
            <p>Tokens are a virtual currency used within the Platform. They can be earned through ad viewing, referrals, and purchases. Tokens have no cash value and are non-transferable. We reserve the right to modify the token system.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>6. Acceptable Use</h2>
            <p>You agree not to: (a) use the Platform for illegal purposes; (b) attempt to reverse-engineer our AI models; (c) share account access; (d) upload malicious content; (e) overwhelm our systems with automated requests beyond normal usage.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>7. Intellectual Property</h2>
            <p>Content generated by our AI tools belongs to you. The Platform, its features, and underlying technology remain our intellectual property. You may not copy, modify, or distribute our platform code.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>8. Limitation of Liability</h2>
            <p>AI Empire provides tools on an &quot;as-is&quot; basis. We are not liable for decisions made based on AI-generated outputs. Our total liability shall not exceed the amounts paid by you in the preceding 12 months.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>9. Termination</h2>
            <p>We may suspend or terminate your account for violation of these terms. You may delete your account at any time through your profile settings.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>10. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="mailto:support@aiempire.app" className="hover:underline" style={{ color: 'var(--accent)' }}>support@aiempire.app</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
